### ISSUE TITLE
build/use better image downscaler

### ISSUE THREAD

**Issue by amhenikoff** [phultquist/smart-album-cover#14]

**Comment by phultquist** [comment]
Why did you close it

**Comment by amhenikoff** [comment]
it was an accident

**Comment by phultquist** [comment]
## worked on it today

in the [resize](https://github.com/phultquist/resize) repository see `resize.py` which contains the algorithm, which just averages a set of pixels. Looking into more advanced algorithms soon.

**Comment by phultquist** [comment]
still have to implement it into the main code.

**Comment by phultquist** [comment]
almost done. see `resize.py`.

algorithm boosts contrast as well because it looks better
