### ISSUE TITLE
after 5 min of paused shut off screen

### ISSUE THREAD

**Issue by amhenikoff** [phultquist/smart-album-cover#19]

**Comment by phultquist** [comment]
this is almost done but I was thinking 1 min? @amhenikoff 

I feel like 5 min is a lil long especially if it turns on super quick

**Comment by amhenikoff** [comment]
okay

**Comment by phultquist** [comment]
Done, time to shutoff in [index.py:main](https://github.com/phultquist/smart-album-cover/blob/spotify-listener/index.py#L127)

It is currently set to 60 seconds @amhenikoff

**Comment by phultquist** [comment]
pull to get the latest and confirm that it works if you can

**Comment by phultquist** [comment]
update it's on `spotify.py`, variable `shutoff_time`
