### ISSUE TITLE
if spotify tells us we sent too many requests, restart program

### ISSUE THREAD

**Issue by amhenikoff** [phultquist/smart-album-cover#21]

**Comment by phultquist** [comment]
i don't how spotify says this

**Comment by phultquist** [comment]
can you paste error code

**Comment by phultquist** [comment]
@amhenikoff please paste error code so I can tell when it's broken

**Comment by amhenikoff** [comment]
I haven't seen this error for a while. I'll post it if I see it though.

**Comment by phultquist** [comment]
Okay, i've updated it. I just wrapped everything in `try catch`, meaning if there is any error it just waits for 5 seconds. I think that I'll probably make it restart the pi, but whatever.

**Comment by amhenikoff** [comment]
HTTP Error for GET to https://api.spotify.com/v1/me/player/currently-playing returned 401 due to The access token expired
http status: 401, code:-1 - https://api.spotify.com/v1/me/player/currently-playing:
 The access token expired
