### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by phultquist** [phultquist/smart-album-cover#24]
Include a settings page with the following settings
- contrast (gamma in resize.py)
- brightness
- autobrightness on/off
- auto-off (default is 1min)
- animation on/off
- animation length (simple slider, discrete)
- spotify configuration and stuff

**Comment by phultquist** [comment]
@amhenikoff add more

**Comment by phultquist** [comment]
- night mode w/ orange tint

**Comment by phultquist** [comment]
make sure to
- kill page if websocket closed
- add default values

**Comment by amhenikoff** [comment]
I think we should have a basic settings/quick settings menu, and then an advanced settings menu for stuff that's a little more confusing, and not required to use the Frame. This is my everything I can think of to add as a feature that needs control in the app:

Basic settings:

Listen mode or Connect mode
brightness
auto-brightness on/off
auto-off timer (default is 1min)
animation length (simple slider, discrete, the minimum value is zero, where no animation exists)
Spotify/Tidal/Pandora/Qobuz login
Night mode (orange tint) + scheduling tool
Clock mode + regular time/military time
Off mode (for lights-out listening/clock mode, if light sensor is less than some super low value like 0.5, then don't turn on at all)

advanced settings:

contrast/saturation (gamma in resize.py)
led nonlinearity correction (gamma in nonlinearity.py)
Minimum brightness (default is 0.07, but the user should be allowed to adjust it lower if they would like)
pause screen logo location (BL, BR, TL, TR, center) & size (S, M, L)
character&background-color for clock mode
Off mode sensitivity threshold setting
Microphone recording wait time from end of previous song (default 15s)
Reset all settings to defaults button (if they screw it up for some reason, they can always get back)

**Comment by phultquist** [comment]
yes sounds good i like these although all of the logins for the different services is going to be tough. will work on it. have to compile list of things to do.

**Comment by phultquist** [comment]
oh my there are so many settings, 90% of them unnecessary. i can see why you're an android user

**Comment by phultquist** [comment]
revised list (ever heard of a bullet point?)

- Rename frame
- Listen mode/Connect mode (rename connect?)
- brightness
- auto-brightness on/off
- auto-off timer (default is 1min)
- animation length (simple slider, discrete, the minimum value is zero, where no animation exists)
- Spotify/Apple Music/Tidal/Pandora/Qobuz login
- Night mode (orange tint) + scheduling tool
- Clock mode + regular time/military time
- Auto Sleep (for lights-out listening/clock mode, if light sensor is less than some super low value like 0.5, then don't turn on at all)

advanced settings:

- contrast/saturation (gamma in resize.py)
- led nonlinearity correction (gamma in nonlinearity.py)
- Minimum brightness (default is 0.07, but the user should be allowed to adjust it lower if they would like)
- ~~pause screen logo location (BL, BR, TL, TR, center) & size (S, M, L)~~
- ~~character&background-color for clock mode~~
- ~~Off mode~~ Auto Sleep ~~sensitivity threshold setting~~ timer 
- Microphone recording wait time from end of previous song (default 15s)
- Reset all settings to defaults button (if they screw it up for some reason, they can always get back)

**Comment by amhenikoff** [comment]
Okay, but that's why it's called an advanced setting. Maybe the clock mode color was a little much, but I think the location of the pause button should be adjustable. What's so special about the bottom right corner?

**Comment by phultquist** [comment]
Nothing considering it's on the bottom left corner

**Comment by amhenikoff** [comment]
Exactly my point, it's so random that I forgot which corner it was.

**Comment by phultquist** [comment]
Is there a spot that is better?

**Comment by phultquist** [comment]
I think we move it to middle
Shouldn't be an option though... that's a dumb change

**Comment by amhenikoff** [comment]
If we move it to the middle, it has to get 2x bigger, or else it's off center. I like it small and in the corner, but it's very reasonable not to. What, do you want Quick settings, Advanced settings, and Extra Advanced settings?

**Comment by phultquist** [comment]
No. I don't want quick settings, advanced settings, and extra advanced settings. that's why this shouldn't be a setting. That's **totally unnecessary** and only makes things **cluttered and stupid**. 

The pause button location is the worst idea for a setting of all time. If bottom right _is not_ the best spot, then we should choose a new spot globally. But there's no reason from one user to another a different pause button location matters. 

This is one of those settings that nobody cares enough and it is just ugly and stupid. If the user really cares that much, then they can clone the repo themselves.

This cannot be a setting. It only clogs things up.

**Comment by amhenikoff** [comment]
Fine, then it should be centered, and 6x6 pixels instead of 3x3. We might have to make it slightly dimmer too because it has a greater area now, and we want it to be comfy.

**Comment by phultquist** [comment]
4x4 is better

![Screen Shot 2020-09-07 at 11 07 29 PM](https://user-images.githubusercontent.com/46694203/92432121-e9cd7f00-f15e-11ea-9fbd-fb4a63180234.png)

**Comment by amhenikoff** [comment]
Too skinny in my opinion.

**Comment by phultquist** [comment]
![Screen Shot 2020-09-07 at 11 09 32 PM](https://user-images.githubusercontent.com/46694203/92432228-33b66500-f15f-11ea-978e-58f8d7dea956.png)

**Comment by phultquist** [comment]
@amhenikoff

**Comment by amhenikoff** [comment]
yeah wait that's ugly too

**Comment by amhenikoff** [comment]
Actually, I do prefer 6x6. When you include the pixel borders, the 6x6 gets slimmer and more reasonable, while the 4x4 looks way too thin.

**Comment by amhenikoff** [comment]
<img width="320" alt="Screen Shot 2020-09-07 at 11 21 33 PM" src="https://user-images.githubusercontent.com/18370553/92432807-e3400700-f160-11ea-8d4f-bfe6dfcab104.png">

**Comment by amhenikoff** [comment]
<img width="321" alt="Screen Shot 2020-09-07 at 11 22 12 PM" src="https://user-images.githubusercontent.com/18370553/92432842-f8b53100-f160-11ea-947c-9d7eaa5e6a8e.png">

**Comment by phultquist** [comment]
okay if you `git pull` it should be updated

**Comment by phultquist** [comment]
Talked about it in messenger... we don't need a pause buttoN!

**Comment by amhenikoff** [comment]
Appended list:

Quick Settings:
- Listen mode/Connect mode
- brightness + auto-brightness on/off (default: 0.5, on)
- Spotify/Apple Music/Tidal/Pandora/Qobuz login
- Clock mode + regular time/military time (default: off, regular time)
- Autosleep (for lights-out listening/clock mode, if light sensor is less than some super low value like 0.5, then don't turn on at all) (default: off)
- Night mode (orange tint) + scheduling tool (default: off)
- animation length (simple slider, discrete, the minimum value is zero, where no animation exists) (default: 12 frames)

Advanced settings:
- Rename frame (default: Name of Purchaser)
- contrast/saturation (gamma in resize.py)
- led nonlinearity correction (gamma in nonlinearity.py)
- Minimum brightness (default is 0.07, but the user should be allowed to adjust it lower if they would like)
- Auto Sleep + sensitivity threshold setting (default: off)
- Mini bottom right pause button on/off + auto-off timer (default is 1min) (default: off)
- Microphone recording wait time from end of previous song (default 15s)
- "Reset all settings to defaults" button (if they screw it up for some reason, they can always get back)

**Comment by phultquist** [comment]
Minimum brightness should not be a setting

**Comment by phultquist** [comment]
And auto sleep should be scheduled

**Comment by phultquist** [comment]
And microphone wait time should not be a setting

**Comment by phultquist** [comment]
You have to think of this as if you're the user. You just want it to work. You don't want to know how it works or exactly what it does... you just want it to work.

**Comment by phultquist** [comment]
As in I don't think contrast should be a setting either

I know I had this initially but it's not significant

**Comment by phultquist** [comment]
Clock mode getting renamed to "show clock"

**Comment by phultquist** [comment]
Just because you _can_ change it does not mean you _should_

**Comment by phultquist** [comment]
Appended list:

Quick Settings:
- Listen mode/Connect mode (default: listen)
- brightness + auto-brightness on/off (default: 0.5, on)
- Spotify/Apple Music/Tidal/Pandora/Qobuz login
- Clock mode + regular time/military time (default: off, regular time)
- **Autosleep (scheduled) (default: off)**
- Night mode (orange tint) + scheduling tool (default: off)
- **animation length (simple slider, fast/normal/slow/off) (default: 12 frames)**

Advanced settings:
- Rename frame (default: {Name of Purchaser}'s Frame)
- Mini bottom right pause button on/off + auto-off timer (default is 1min) (default: off) **im debating if the timer is necessary**
- "Reset all settings to defaults" button (if they screw it up for some reason, they can always get back)

**Comment by phultquist** [comment]
i bolded the ones that i changed and deleted a lot

i can already hear you complaining "well it doesn't hurt to be able to change the setting..." 

it does hurt. it makes things cluttered and unclear, and the end user doesn't really know what any of these mean. Like "nonlinearity compensation?" Why would a user care? These are things that they shouldn't know. It needs to be presented as a piece as a whole, not a complex machine with moving parts. It's a slab of glass not a gear engine. 

It needs to be simple, easy, intuitive. What you're asking for is ugly and... gross.

**Comment by amhenikoff** [comment]
I was actually just thinking about this and I was about to say we that we do need some settings, but having too many settings makes the user's opinion of the Frame more important that ours, which makes it seem more like a consumer product than art.

**Comment by phultquist** [comment]
Too many settings makes it feel like a pc

**Comment by phultquist** [comment]
yeah we don't need a timer for the pause button that is dumb

**Comment by phultquist** [comment]
Edited list:

Home:
- Listen mode/Connect mode (default: listen)
- brightness + auto-brightness on/off (default: 0.5, on)
- Spotify/Apple Music/Tidal/Pandora/Qobuz login
- Clock mode + regular time/military time (default: off, regular time)
- **Autosleep (scheduled) (default: off)**
- Night mode (orange tint) + scheduling tool (default: off)
- **animation length (simple slider, fast/normal/slow/off) (default: 12 frames)**

Advanced settings:
- Rename frame (default: {Name of Purchaser}'s Frame)
- Mini bottom right pause button on/off (default: off)
- "Reset all settings to defaults" button (if they screw it up for some reason, they can always get back)

**Comment by phultquist** [comment]
night mode makes me want to puke
