### ISSUE TITLE
Manual Codeword-based pairing

### ISSUE THREAD

**Issue by amhenikoff** [phultquist/smart-album-cover#28]

**Comment by phultquist** [comment]
can you make this into a global pairing schema

explaining exactly how pairing is going to work

**Comment by phultquist** [comment]
like the pairing is one task

**Comment by amhenikoff** [comment]
This pairing mode uses a codeword/phrase that is printed on the back of the Frame, permanently associated with that specific device. Once the Frame gets a stable internet connection, it sends its local ip up to the server. The user visits a site, where they type in the codeword and receive a link to the local ip of the Frame, which directs the user to a locally hosted settings page.
