### ISSUE TITLE
Clock Mode

### ISSUE THREAD

**Issue by amhenikoff** [phultquist/smart-album-cover#30]
I can do the number/character designs.

**Comment by phultquist** [comment]
i don't know about this one... i've been thinking about it

should it just be an option? Like instead of turning off after 1 min, it shows a clock? I think this is a feasible solution.

**Comment by amhenikoff** [comment]
That's what I was picturing. How else would it work?

**Comment by phultquist** [comment]
okay makes sense. would have to do 8x8 numbers.

let's keep clock mode very dim

**Comment by amhenikoff** [comment]
I think we can easily make them fit in 7x7 so that there's a 2-pixel gap between the numbers, and most numbers have either horizontal or vertical symmetrical features, which make an odd number of pixels for the characters very nice. I have it drawn out in the spreadsheet.

**Comment by amhenikoff** [comment]
<img width="321" alt="Screen Shot 2020-09-08 at 11 53 43 AM" src="https://user-images.githubusercontent.com/18370553/92505607-f3d89780-f1c9-11ea-9168-d1f259b7c9a6.png">
<img width="321" alt="Screen Shot 2020-09-08 at 11 54 05 AM" src="https://user-images.githubusercontent.com/18370553/92505640-005cf000-f1ca-11ea-805f-c4dbdceea5a6.png">
<img width="321" alt="Screen Shot 2020-09-08 at 11 54 31 AM" src="https://user-images.githubusercontent.com/18370553/92505762-1074cf80-f1ca-11ea-880f-03019c70d538.png">
I like all of them, but I think #1 might be a lil wide, so I think the options should be flat or 3D with an accent color.

**Comment by amhenikoff** [comment]
I think #1 should stay because the digits are exactly as tall as they are wide, and so they fill out the Frame well. I don't love the bezels on #2, but they aren't noticeable on #3 because it looks so damn cool.

**Comment by amhenikoff** [comment]
If we want to only have 2 choices, I vote #1 and #3.
