### ISSUE TITLE
To do before October 3rd

### ISSUE THREAD

**Issue by phultquist** [phultquist/smart-album-cover#37]
# To do before October 3rd

1. Create on start script that starts program, creates web socket server, and hosts react app
2. Add spotify/listening mode to react app
3. Fix autobrightness
4. Cut wood

**Comment by phultquist** [comment]
@amhenikoff look good?

**Comment by amhenikoff** [comment]
also 
5. get run on boot fully working
6. Take contrast off settings site
7. Uncenter "Patrick's Frame" on Settings Site - move to top left it looks tacky

**Comment by phultquist** [comment]
@amhenikoff we have a lot of work to do tonight
### Things to do tonight
1. Secure listening (make it display)
2. Set up listening trigger
3. Set up spotify/listening switch
4. Wifi connect on start; then, run run.py script
5. Three successful, consecutive test runs (including wifi setup on a new network)
